spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/community?allowPublicKeyRetrieval=true&useSSL=false
    username: # db_userId
    password: # db_password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /console
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: # client-id
            client-secret: # client-secret
          facebook:
            client-id: # client-id
            client-secret: # client-secret
custom:
  oauth2:
    kakao:
      client-id: # client-id
